services:
  postgres:
    image: postgres:15 # Версия PostgreSQL
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres          # Имя пользователя
      POSTGRES_PASSWORD: 12345678      # Пароль пользователя
      POSTGRES_DB: postgres            # Название базы данных
    ports:
      - "5432:5432"                    # Порт для подключения к БД
    volumes:
      - postgres_data:/var/lib/postgresql/data # Постоянное хранилище данных
    restart: always

volumes:
  postgres_data: # Объем для хранения данных PostgreSQL